PROMPT Creating OptiDock auth and chat storage tables...

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE optidock_users (
            user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            email VARCHAR2(320) NOT NULL,
            full_name VARCHAR2(255) NOT NULL,
            workspace_name VARCHAR2(255) NOT NULL,
            password_hash VARCHAR2(512) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT optidock_users_email_uk UNIQUE (email)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE TABLE optidock_chat_context (
            context_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            session_key VARCHAR2(128),
            context_label VARCHAR2(255),
            context_payload CLOB,
            prompt_text CLOB NOT NULL,
            prompt_hash VARCHAR2(64),
            response_text CLOB,
            response_hash VARCHAR2(64),
            context_hash VARCHAR2(64),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT optidock_chat_context_user_fk
                FOREIGN KEY (user_id) REFERENCES optidock_users (user_id)
        )
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX optidock_chat_context_user_idx
            ON optidock_chat_context (user_id, created_at)
    ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE TRIGGER optidock_users_touch_trg
BEFORE UPDATE ON optidock_users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER optidock_chat_hashes_trg
BEFORE INSERT OR UPDATE ON optidock_chat_context
FOR EACH ROW
BEGIN
    IF :NEW.prompt_text IS NOT NULL THEN
        :NEW.prompt_hash := STANDARD_HASH(:NEW.prompt_text, 'SHA256');
    END IF;

    IF :NEW.response_text IS NOT NULL THEN
        :NEW.response_hash := STANDARD_HASH(:NEW.response_text, 'SHA256');
    END IF;

    IF :NEW.context_payload IS NOT NULL THEN
        :NEW.context_hash := STANDARD_HASH(:NEW.context_payload, 'SHA256');
    END IF;
END;
/

PROMPT OptiDock auth bootstrap complete.
